name: steps example

on:
  push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      - id: step-caller
        uses: "./.github/actions/hello"
        with:
          the-caller: "Myself"
      - run: echio ${{ steps.step-caller.outputs.random-number }}
        shell: bash
